server:
    port: 80
    
spring:
   datasource:
       url:   jdbc:mysql://127.0.0.1/c83-s3-pzm-blog?useUnicode=true&characterEncoding=UTF-8
       username:  root
       password:  a
       driver-class-name:  com.mysql.jdbc.Driver        

#日志配置
logging:
    level:
      com:
         yc:
           C83S3Pzmblog:
             dao: debug  
             web: warn