server:
    port: 80
    
# 定义当前服务名
spring:
   application:
      name: crzuul
      
# 解决 zuul 网关报错的问题      
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
     ConnectTimeout: 3000
     ReadTimeout: 60000  