# yml 文件不能使用制表符空格tab ,只能使用普通空格表示缩进
# 设置值  使用：空格（值）
server:
   port:  80
 
spring:
   datasource:
       url:   jdbc:mysql://127.0.0.1/a?useUnicode=true&characterEncoding=UTF-8
       username:  root
       password:  a
       driver-class-name:  com.mysql.jdbc.Driver  
       
#邮件发送 Yml 配置规则：如果某个阶段有重复配置情况，必须要合并
   mail:
       #邮箱服务器地址
       host: stmp.qq.com
       #用户名
       username: 18372728602@qq.com
       #密码
       password: jbxpqjujqzfcdfai
       default-encoding: UTF-8
       
       
#日志配置
logging:
    level:
      com:
         yc:
           C83S3PzmSpringBoot:
             dao: debug  
             web: warn
             
#以谁来发送邮件 ==>用户自定义的属性
mail:
   formMail:
       addr: 1837278602@qq.com                         
